package Modelo;
// Generated 05/05/2018 19:47:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private String apellido;
     private String dni;
     private Date fechaNaci;
     private String direccion;
     private Integer telefono;

    public Cliente() {
    }

	
    public Cliente(String nombre, String apellido, String dni) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.dni = dni;
    }
    public Cliente(String nombre, String apellido, String dni, Date fechaNaci, String direccion, Integer telefono) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaNaci = fechaNaci;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   

    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNaci() {
        return this.fechaNaci;
    }
    
    public void setFechaNaci(Date fechaNaci) {
        this.fechaNaci = fechaNaci;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    @Override
    public String toString() {
        return "Cliente{" + "codigo=" + codigo + ", nombre=" + nombre + ", apellido=" + apellido + ", dni=" + dni + ", fechaNaci=" + fechaNaci + ", direccion=" + direccion + ", telefono=" + telefono + '}';
    }




}


