package Modelo;
// Generated 01/03/2020 02:51:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String apellido;
     private String dni;
     private Date fechaNaci;
     private String direccion;
     private int telefono;

    public Cliente() {
    }

   /* public Cliente(int codigo, String nombre, String apellido, String dni, Date fechaNaci, String direccion, int telefono) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaNaci = fechaNaci;
       this.direccion = direccion;
       this.telefono = telefono;
    }*/
    public Cliente(String nombre, String apellido, String dni, Date fechaNaci, String direccion, Integer telefono) {
        this.nombre = nombre;
       this.apellido = apellido;
       this.dni = dni;
       this.fechaNaci = fechaNaci;
       this.direccion = direccion;
       this.telefono = telefono;    }

   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNaci() {
        return this.fechaNaci;
    }
    
    public void setFechaNaci(Date fechaNaci) {
        this.fechaNaci = fechaNaci;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }




}


